apiVersion: v1
kind: Namespace
metadata:
  name: astralytiq
  labels:
    name: astralytiq
    app.kubernetes.io/name: astralytiq
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: astralytiq-platform